myName =input("What's your name?")
favFood =input("What's your favourite food?")
favMusic=input("What's your favourite music?")
location=input("Where do you live?")
 
print()
print("So, you're")
print(myName)
print("You seem hungry for")
print(favFood)
print("You can order via Glovo app and they wil deliver at your doorstep in")
print(location)
print("While waiting, you can be listening to")
print(favMusic)
print("🙂" )