print("=== Welcome to the adventure simulators ===")
print("""I am going to ask you a bunch of questions
      and then create an epic story with you as the star!😘""")
print()
name = input("Your name?:")
enemy = input("Your worst enemy's name?:")
superPower = input("What is your superpower?:")
live = input("Where do you live?:")
food = input("What is your favourite food?:")
print()
print("Hello", name, "Your ability to", superPower,)
print("will make sure you never have to look at", enemy, "again.")
print("Go eat", food, "as you walk down the streets of", live,)
print("and use", superPower, "\033[31m", "for good and not evil!", "\033[0m")